version: '3.8'

services:
  reddit-service-backend:
    image: reddit-service-backend:latest
    restart: always
    networks:
      - bridge
      - reddit-service-backend
    ports:
      - "80:3000/tcp"
    environment:
      NODE_ENV: 'production'

networks:
  bridge:
    driver: bridge
  reddit-service-backend:
    internal: true
