version: '3.8'

services:
  reddit-service-backend:
    image: reddit-service-backend:develop
    build:
      context: .
      target: development
    restart: unless-stopped
    volumes:
      - .:/opt/reddit-service-backend

  mongo:
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    networks:
      - bridge
      - reddit-service-backend
    ports:
      - "8081:8081/tcp"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOSTNAME}

  redis:
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    networks:
      - bridge
      - reddit-service-backend
    ports:
      - "8082:8081/tcp"
    environment:
      - REDIS_HOSTS=local:redis:6379
