version: '3.8'

services:
  reddit-service-backend:
    image: reddit-service-backend:develop
    build:
      context: .
      target: development
    restart: unless-stopped
    volumes:
      - .:/opt/reddit-service-backend
