version: '3.8'

services:
  reddit-service-backend:
    image: reddit-service-backend:latest
    restart: always
    networks:
      - bridge
      - reddit-service-backend
    ports:
      - "80:3000/tcp"
    volumes:
      - .env:/opt/reddit-service-backend/.env

networks:
  bridge:
    driver: bridge
  reddit-service-backend:
    internal: true
